package:
  format-version: "1.0.0"
  name: "csp_apps_pic32ck_sg_gc"
  version: "v3.0.0-E2"
  type: "application"
  status: "production"
  required: true

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.16.0-E1"


