package:
  format-version: "1.0.0"
  name: "csp_apps_pic32ck_sg_gc"
  version: "v3.0.1"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.18.5"